# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Fieldsize', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuardianFirstName', models.CharField(max_length=300)),
                ('GuardianLastName', models.CharField(max_length=300)),
                ('PlayerFirstName', models.CharField(max_length=300)),
                ('PlayerLastName', models.CharField(max_length=300)),
                ('DateOfBirth', models.DateField()),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Zipcode', models.IntegerField()),
                ('PhoneNumber', models.IntegerField()),
                ('Level', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionDescrip', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('FieldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('DivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=300)),
                ('LastName', models.CharField(max_length=300)),
                ('DateOfBirth', models.DateField()),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Zipcode', models.IntegerField()),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=300)),
                ('Returning', models.CharField(max_length=300)),
                ('Children', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('PositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position')),
                ('VolunteerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='VolunteerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer'),
        ),
        migrations.AddField(
            model_name='roster',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='VolunteerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer'),
        ),
    ]
