# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='FieldName',
            field=models.IntegerField(choices=[(0, ''), (1, 'Field 1'), (2, 'Field 2'), (3, 'Field 3'), (4, 'Field 4')], default=0),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
