# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160405_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='FieldID',
        ),
    ]
