# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_reservation_volunteerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='Location',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='field',
            name='Fieldsize',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='FieldName',
        ),
        migrations.AddField(
            model_name='field',
            name='FieldName',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='Street',
            field=models.CharField(default=datetime.datetime(2016, 4, 7, 17, 21, 7, 128201, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='FieldID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='VolunteerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer'),
            preserve_default=False,
        ),
    ]
