# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160413_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='DateOfBirth',
        ),
        migrations.AddField(
            model_name='player',
            name='DateOfBirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='GuardianLastName',
        ),
        migrations.AddField(
            model_name='player',
            name='GuardianLastName',
            field=models.CharField(max_length=300, verbose_name='Guardian Last Name'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='player',
            name='PhoneNumber',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='PlayerFirstName',
        ),
        migrations.AddField(
            model_name='player',
            name='PlayerFirstName',
            field=models.CharField(max_length=300, verbose_name='Player First Name'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='PlayerLastName',
        ),
        migrations.AddField(
            model_name='player',
            name='PlayerLastName',
            field=models.CharField(max_length=300, verbose_name='Player Last Name'),
        ),
    ]
