# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160413_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='Children',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Children',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='DateOfBirth',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='DateOfBirth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='FirstName',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='FirstName',
            field=models.CharField(max_length=300, verbose_name='First Name'),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='LastName',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='LastName',
            field=models.CharField(max_length=300, verbose_name='Last Name'),
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='PhoneNumber',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
