# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160413_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Level',
            field=models.IntegerField(choices=[(0, ''), (1, 'PeeWee'), (2, 'Minors'), (3, 'Majors')], default=0),
        ),
    ]
