# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160414_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Level',
            field=models.IntegerField(choices=[(0, ''), (1, 'PeeWee (Ages 8-10)'), (2, 'Minors (Ages 10-12)'), (3, 'Majors (Ages 12-14)')], default=0),
        ),
    ]
