# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160414_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='Picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
