# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Time',
            field=models.IntegerField(choices=[(0, ''), (1, '8:00 AM - 10:00 AM'), (2, '10:00 AM - 12:00 PM'), (3, '12:00 PM - 2:00 PM'), (4, '2:00 PM - 4:00 PM'), (5, '4:00 PM - 6:00 PM')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date',
            field=models.DateField(),
        ),
    ]
