# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160416_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='GuardianFirstName',
            field=models.CharField(max_length=300, verbose_name='Guardian First Name'),
        ),
    ]
