# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20160419_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='FieldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Field', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='VolunteerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer', verbose_name='Coach'),
        ),
    ]
