# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20160419_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='player',
            name='PhoneNumber',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
    ]
