# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20160419_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='PhoneNumber',
            field=models.CharField(help_text='Please use the following format: <em>555-555-5555</em>.', max_length=50, verbose_name='Phone Number'),
        ),
    ]
