# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20160422_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Zipcode',
            field=models.IntegerField(default=32323, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
